version: '3'
services:
  setup:
    build:
      context: ../docker
      dockerfile: $TEE/$TEE-setup.Dockerfile
    env_file: ../.env
    environment:
      NEW: $NEW
    volumes:
      - sync:/home/provable/sync
      - ../enclave-proxy:/home/provable/proxy
    network_mode: host

  syncer_native:
    image: provable/ptokens-${NATIVE_SYMBOL}-syncer:1.13.0-${TEE}
    env_file: ../.env
    volumes:
      - pnpm-store:/home/provable/.pnpm-store
      - sync:/home/provable/sync
      - syncer_native_nm:/home/provable/syncer/node_modules
      - ../enclave-proxy:/home/provable/proxy
    network_mode: host
    restart: unless-stopped

  syncer_host:
    image: provable/ptokens-${HOST_SYMBOL}-syncer:1.6.0-${TEE}
    env_file: ../.env
    volumes:
      - pnpm-store:/home/provable/.pnpm-store
      - sync:/home/provable/sync
      - syncer_host_nm:/home/provable/syncer/node_modules
      - ../enclave-proxy:/home/provable/proxy
    network_mode: host
    restart: unless-stopped

  api:
    image: provable/ptokens-api-server:1.9.0-vanilla
    env_file: ../.env
    volumes:
      - sync:/home/provable/sync
      - api_server_nm:/home/provable/api-server/node_modules
    network_mode: host
    restart: unless-stopped

  smart_contract_generator:
    image: provable/ptokens-erc777-smart-contract:2.1.4
    command:
      - --token-name="$SMART_CONTRACT_TOKEN_NAME"
      - --token-symbol=$SMART_CONTRACT_NATIVE_SYMBOL
      - --default-operators=$SMART_CONTRACT_DEFAULT_OPERATOR
    env_file: ../.env
    environment:
      NEW: $NEW
    volumes:
      - sync:/home/provable/sync
      - build:/home/provable/generator/build
      - smart_contract_generator_nm:/home/provable/generator/node_modules
    network_mode: host

volumes:
  sync:
  build:
  pnpm-store:
  api_server_nm:
  syncer_host_nm:
  syncer_native_nm:
  broadcaster_host_nm:
  broadcaster_native_nm:
  smart_contract_generator_nm:
